name: Compilar Tesis LaTeX

on:
  push:
    branches: [ "main" ] # Se ejecuta cada vez que subes a la rama main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Compilar documento LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          # Si tu archivo .tex principal está en una subcarpeta, descomenta y ajusta esta línea:
          # working_directory: "Tesis/Latex/" 
          root_file: "main.tex"
          compiler: latexmk # latexmk es ideal porque maneja bibliografía e índices automáticamente

      - name: Guardar el PDF como Artefacto
        uses: actions/upload-artifact@v4
        with:
          name: Tesis-PDF
          # Ajusta la ruta si usaste working_directory arriba
          path: "main.pdf"